.PHONY: test lint tidy fix format check build build-release install \
       play detect detect-mask background pipeline pipeline-metal capture benchmark-simd benchmark-coreml benchmark-metal isp export-coreml \
       docker-build docker-asan docker-tsan docker-valgrind docker-all docker-shell docker-clean

# ── Build ─────────────────────────────────────────────────
JOBS ?= $(shell sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4)

build:
	cmake -B build -DCMAKE_BUILD_TYPE=Debug -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build -j$(JOBS)

build-release:
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build -j$(JOBS)

install:
	python3.12 -m venv .venv
	.venv/bin/pip install -r requirements.txt

# ── Test & Lint ───────────────────────────────────────────
test:
	ctest --test-dir build --output-on-failure
	PYTHONPATH=build .venv/bin/python -m pytest tests/ -v

lint:
	.venv/bin/ruff check src/ tests/ tools/

# clang-tidy: static analysis for C++ (bugprone, performance, modernize).
# Requires build/ with compile_commands.json (generated by cmake).
tidy:
	clang-tidy -p build src/cpp/simd/*.cpp src/cpp/bindings/*.cpp \
		src/cpp/frame_pipeline/*.cpp src/cpp/objcpp/*.cpp tests/cpp/*.cpp

fix:
	.venv/bin/ruff check --fix src/ tests/ tools/

format:
	.venv/bin/ruff format src/ tests/ tools/

check: lint tidy test

# ── Tools (URL required) ─────────────────────────────────
URL ?= https://s53.nysdot.skyvdn.com:443/rtplive/TA_028/playlist.m3u8

play:
	.venv/bin/python tools/stream_player.py --url "$(URL)"

detect:
	PYTHONPATH=build .venv/bin/python tools/detection_viewer.py --url "$(URL)" --vehicles-only

detect-mask:
	PYTHONPATH=build .venv/bin/python tools/detection_viewer.py --url "$(URL)" --vehicles-only --show-mask

background:
	PYTHONPATH=build .venv/bin/python tools/background_viewer.py --url "$(URL)"

pipeline:
	PYTHONPATH=build .venv/bin/python tools/pipeline_viewer.py --url "$(URL)" --vehicles-only

pipeline-metal:
	PYTHONPATH=build .venv/bin/python tools/pipeline_viewer.py --url "$(URL)" --vehicles-only --metal

capture:
	.venv/bin/python tools/capture_frames.py --url "$(URL)" --count 200

benchmark-simd:
	@echo "=== Release build ==="
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build -j$(JOBS)
	PYTHONPATH=build .venv/bin/python tools/benchmark_simd.py

benchmark-coreml:
	@echo "=== Release build ==="
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build -j$(JOBS)
	PYTHONPATH=build .venv/bin/python tools/benchmark_coreml.py

benchmark-metal:
	@echo "=== Release build ==="
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build -j$(JOBS)
	PYTHONPATH=build .venv/bin/python tools/benchmark_metal.py

isp:
	PYTHONPATH=build .venv/bin/python tools/isp_viewer.py --url "$(URL)"

export-coreml:
	.venv/bin/python tools/export_pt2coreml.py yolo
	.venv/bin/python tools/export_pt2coreml.py realesrgan

# ── Docker (sanitizer + Valgrind testing on Linux) ───────
# OpenCV is skipped on Linux (all OpenCV-dependent code is macOS-only).
# Only our SIMD/frame code + GoogleTest build — takes ~30s not ~10min.
# Sanitizer flags are per-target (streetscope_warnings interface library).
DOCKER_IMAGE = streetscope-test
DOCKER_RUN   = docker run --rm -v $(CURDIR):/app -w /app $(DOCKER_IMAGE)

docker-build:
	docker build -t $(DOCKER_IMAGE) .

# ASan + UBSan: memory errors (buffer overflow, use-after-free, etc.)
# LSan (leak detection) is built into ASan on Linux and runs automatically.
# C++ tests only — Python's arena allocator produces LSan false positives
# and pytest under LD_PRELOAD is slow/noisy with no sanitizer benefit.
docker-asan:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=ON \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker -j$(JOBS) \
		&& ASAN_OPTIONS=abort_on_error=1 \
		ctest --test-dir build-docker --output-on-failure'

# TSan: data races, deadlocks, lock-order inversions.
# Mutually exclusive with ASan — separate build required.
# C++ tests only — same rationale as docker-asan.
docker-tsan:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=thread \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker -j$(JOBS) \
		&& TSAN_OPTIONS=second_deadlock_stack=1:suppressions=/app/tsan.supp \
		ctest --test-dir build-docker --output-on-failure'

# Valgrind: memory leaks (more thorough than LSan), uninitialized reads,
# use-after-free. Requires SANITIZE=OFF — Valgrind cannot run on
# ASan/TSan-instrumented binaries. C++ tests only (Valgrind + Python
# is too noisy; use valgrind-python.supp if needed).
docker-valgrind:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=OFF \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker -j$(JOBS) \
		&& for bin in build-docker/test_*; do \
			case "$$bin" in *.cmake|*.txt) continue ;; esac; \
			[ -x "$$bin" ] && [ -f "$$bin" ] || continue; \
			echo "=== Valgrind: $$bin ==="; \
			valgrind --tool=memcheck --leak-check=full --track-origins=yes \
				--error-exitcode=1 "$$bin" || exit 1; \
		done'

# Run all sanitizers: Valgrind (no sanitizers) → TSan → ASan+LSan.
docker-all: docker-valgrind docker-tsan docker-asan

docker-shell:
	docker run --rm -it -v $(CURDIR):/app -w /app $(DOCKER_IMAGE) bash

docker-clean:
	rm -rf build-docker
	docker rmi $(DOCKER_IMAGE) 2>/dev/null || true
	docker builder prune -f --filter label=com.docker.compose.project 2>/dev/null || true
	docker system prune -f
