.PHONY: test lint tidy fix format check build build-release install \
       play detect detect-mask background pipeline capture benchmark-simd isp export-coreml \
       docker-build docker-asan docker-tsan docker-valgrind docker-all docker-shell docker-clean

# ── Build ─────────────────────────────────────────────────
build:
	cmake -B build -DCMAKE_BUILD_TYPE=Debug -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build

build-release:
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build

install:
	python3.12 -m venv .venv
	.venv/bin/pip install -r requirements.txt

# ── Test & Lint ───────────────────────────────────────────
test:
	ctest --test-dir build --output-on-failure
	PYTHONPATH=build .venv/bin/python -m pytest tests/ -v

lint:
	.venv/bin/ruff check src/ tests/ tools/

# clang-tidy: static analysis for C++ (bugprone, performance, modernize).
# Requires build/ with compile_commands.json (generated by cmake).
tidy:
	clang-tidy -p build src/cpp/simd/*.cpp src/cpp/bindings/*.cpp tests/cpp/*.cpp

fix:
	.venv/bin/ruff check --fix src/ tests/ tools/

format:
	.venv/bin/ruff format src/ tests/ tools/

check: lint tidy test

# ── Tools (URL required) ─────────────────────────────────
URL ?= https://s53.nysdot.skyvdn.com:443/rtplive/TA_028/playlist.m3u8

play:
	.venv/bin/python tools/stream_player.py --url "$(URL)"

detect:
	.venv/bin/python tools/detection_viewer.py --url "$(URL)" --vehicles-only

detect-mask:
	.venv/bin/python tools/detection_viewer.py --url "$(URL)" --vehicles-only --show-mask

background:
	.venv/bin/python tools/background_viewer.py --url "$(URL)"

pipeline:
	.venv/bin/python tools/pipeline_viewer.py --url "$(URL)" --vehicles-only

capture:
	.venv/bin/python tools/capture_frames.py --url "$(URL)" --count 200

benchmark-simd:
	@echo "=== Debug build ==="
	cmake -B build -DCMAKE_BUILD_TYPE=Debug -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build
	PYTHONPATH=build .venv/bin/python tools/benchmark_simd.py
	@echo ""
	@echo "=== Release build ==="
	cmake -B build -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=.venv/bin/python
	cmake --build build
	PYTHONPATH=build .venv/bin/python tools/benchmark_simd.py

isp:
	.venv/bin/python tools/isp_viewer.py --url "$(URL)"

export-coreml:
	.venv/bin/python tools/export_pt2coreml.py

# ── Docker (sanitizer + Valgrind testing on Linux) ───────
# Toolchain image with source mounted at runtime.
# ASan, TSan, and Valgrind need different builds, so each
# target reconfigures build-docker/ as needed.
DOCKER_IMAGE = streetscope-test
DOCKER_RUN   = docker run --rm -v $(CURDIR):/app -w /app $(DOCKER_IMAGE)

docker-build:
	docker build -t $(DOCKER_IMAGE) .

# ASan + UBSan: memory errors (buffer overflow, use-after-free, etc.)
# LSan (leak detection) is built into ASan on Linux and runs automatically
# for C++ tests (ctest). For Python tests, detect_leaks=0 disables LSan
# because Python's arena allocator produces false positives.
docker-asan:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=ON \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker \
		&& ctest --test-dir build-docker --output-on-failure \
		&& LD_PRELOAD=$$(gcc -print-file-name=libasan.so) \
		ASAN_OPTIONS=detect_leaks=0:abort_on_error=1 \
		PYTHONPATH=build-docker python -m pytest tests/ -v \
			--ignore=tests/python/test_async_detector.py \
			--ignore=tests/python/test_detector.py'

# TSan: data races, deadlocks, lock-order inversions.
# Mutually exclusive with ASan — separate build required.
# second_deadlock_stack=1 prints both lock sites on deadlock.
docker-tsan:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=thread \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker \
		&& TSAN_OPTIONS=second_deadlock_stack=1:suppressions=/app/tsan.supp \
		ctest --test-dir build-docker --output-on-failure \
		&& LD_PRELOAD=$$(gcc -print-file-name=libtsan.so) \
		TSAN_OPTIONS=second_deadlock_stack=1:suppressions=/app/tsan.supp \
		PYTHONPATH=build-docker python -m pytest tests/ -v \
			--ignore=tests/python/test_async_detector.py \
			--ignore=tests/python/test_detector.py'

# Valgrind: memory leaks (more thorough than LSan), uninitialized reads,
# use-after-free. Requires SANITIZE=OFF — Valgrind cannot run on
# ASan/TSan-instrumented binaries. C++ tests only (Valgrind + Python
# is too noisy; use valgrind-python.supp if needed).
docker-valgrind:
	$(DOCKER_RUN) sh -c '\
		cmake -B build-docker -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=OFF \
			-DPython3_EXECUTABLE=$$(which python3) \
		&& cmake --build build-docker \
		&& for bin in build-docker/test_*; do \
			case "$$bin" in *.cmake|*.txt) continue ;; esac; \
			[ -x "$$bin" ] && [ -f "$$bin" ] || continue; \
			echo "=== Valgrind: $$bin ==="; \
			valgrind --tool=memcheck --leak-check=full --track-origins=yes \
				--error-exitcode=1 "$$bin" || exit 1; \
		done'

# Run all sanitizers: Valgrind (no sanitizers) → TSan → ASan+LSan.
# Each reconfigures build-docker/ since they're mutually exclusive.
docker-all: docker-valgrind docker-tsan docker-asan

docker-shell:
	docker run --rm -it -v $(CURDIR):/app -w /app $(DOCKER_IMAGE) bash

docker-clean:
	rm -rf build-docker
	docker rmi $(DOCKER_IMAGE) 2>/dev/null || true
	docker builder prune -f --filter label=com.docker.compose.project 2>/dev/null || true
	docker system prune -f
